### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by 4dvn** [abelykh0/stm32f103-midi#1]
Hello, can you give me the step to compile and upload?

**Comment by abelykh0** [comment]
Run System Workbench for STM32
File > Open Projects from file system, choose folder, Finish
Project > Build Configurations > Set Active > Release
Project > Build Project
Run > Run

**Comment by 4dvn** [comment]
> Run System Workbench for STM32
> File > Open Projects from file system, choose folder, Finish
> Project > Build Configurations > Set Active > Release
> Project > Build Project
> Run > Run

How to modify it to 4x4 keypad? thank you
